unblock/urls.py
from django.conf.urls import url

from . import views

app_name = 'unblock'
urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^(?P<puzzle_id>[0-9]+)/$', views.puzzle, name='puzzle'),
    url(r'^create/$', views.create, name='create'),
]

unblock_test/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^unblock/', include('unblock.urls')),
    url(r'^admin/', admin.site.urls),
    url(r'^accounts/', include('django.contrib.auth.urls')),
]

unblock/models.py
from django.db import models

from django.contrib.auth.models import User


num_rows = 12
num_columns = 6
num_colors = 6  # Maximum 126; must have enough colors defined in play.js
max_stars = 5
max_brains = 5
max_puzzle_name_length = 200


class InvalidRatingError(Exception):
    pass


class Puzzle(models.Model):
    name = models.CharField(max_length=max_puzzle_name_length)
    pub_date = models.DateTimeField('date published', auto_now_add=True)
    creator = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    stars = models.IntegerField(default=0)
    ratings = models.IntegerField(default=0)
    difficulty_points = models.IntegerField(default=0)
    difficulty_ratings = models.IntegerField(default=0)
    # Stored in row-major order from bottom; 0=empty; 1..num_colors=tile color
    tiles = models.BinaryField(
        max_length=num_rows*num_columns,
        default=b'\0'*(num_rows*num_columns)
    )
    moves = models.SmallIntegerField(default=1)
    # TODO: figure out how to make the model depend on app configuration

    def __str__(self):
        return self.name

    def rate(self, num_stars):
        if num_stars < 1 or num_stars > max_stars:
            raise InvalidRatingError()
        self.stars += num_stars
        self.ratings += 1
        self.save()

    def rate_difficulty(self, num_brains):
        if num_brains < 1 or num_brains > max_brains:
            raise InvalidRatingError()
        self.difficulty_points += num_brains
        self.difficulty_ratings += 1
        self.save()

    def rating(self):
        if self.ratings > 0:
            return self.stars / self.ratings
        else:
            return None

    def difficulty_rating(self):
        if self.difficulty_ratings > 0:
            return self.difficulty_points / self.difficulty_ratings
        else:
            return None

unblock/forms.py
from gettext import gettext as _

from django import forms
from django.forms import ValidationError

from .models import num_rows, num_columns, max_puzzle_name_length


empty_char = '\x7F'  # Used instead of 0 for puzzle encoding in forms

def tiles_string_to_list(tiles_str):
    result = []
    for r in range(num_rows):
        result.append([])
        for c in range(num_columns):
            num = ord(tiles_str[num_columns*r+c])
            result[r].append(num if num != ord(empty_char) else 0)
    return result

def validate_no_floating_tiles(tiles_str):
    tiles = tiles_string_to_list(tiles_str)
    for c in range(num_columns):
        for r in range(1, num_rows):
            if tiles[r][c] != 0 and tiles[r-1][c] == 0:
                raise ValidationError(_('Floating tile(s)'), code='floating')

def validate_no_complete_rows_or_columns(tiles_str):
    tiles = tiles_string_to_list(tiles_str)
    for r in range(num_rows):
        for c in range(num_columns-2):
            if tiles[r][c] == tiles[r][c+1] == tiles[r][c+2] != 0:
                raise ValidationError(_('Complete row'), code='complete')
    for r in range(num_rows-2):
        for c in range(num_columns):
            if tiles[r][c] == tiles[r+1][c] == tiles[r+2][c] != 0:
                raise ValidationError(_('Complete column'), code='complete')


class PuzzleForm(forms.Form):
    name = forms.CharField(
        label="Puzzle name", max_length=max_puzzle_name_length
    )
    moves = forms.IntegerField(min_value=1)
    tiles = forms.CharField(
        min_length=num_rows*num_columns,
        max_length=num_rows*num_columns,
        validators=[
            validate_no_floating_tiles,
            validate_no_complete_rows_or_columns
        ],
        widget=forms.widgets.HiddenInput()
    )

unblock/views.py
from django.shortcuts import get_object_or_404, render
from django.contrib.auth.decorators import login_required
from django.http import HttpResponseRedirect
from django.urls import reverse

from .forms import PuzzleForm, empty_char
from .models import Puzzle, num_rows, num_columns, num_colors


canvas_height = 600
canvas_width = canvas_height * num_columns // num_rows
palette_width = 50
palette_height = palette_width * (num_colors+1)

def index(request):
    latest_puzzle_list = Puzzle.objects.order_by('-pub_date')[:10]
    context = { 'latest_puzzle_list': latest_puzzle_list }
    return render(request, 'unblock/index.html', context)

def puzzle(request, puzzle_id):
    p = get_object_or_404(Puzzle, pk=puzzle_id)
    context = {
        'puzzle': p, 'num_rows': num_rows, 'num_columns': num_columns,
        'canvas_width': canvas_width, 'canvas_height': canvas_height,
        'empty_char': empty_char
    }
    return render(request, 'unblock/puzzle.html', context)

@login_required
def create(request):
    if request.method == 'POST':
        form = PuzzleForm(request.POST)
        if form.is_valid():
            Puzzle.objects.create(
                name=form.cleaned_data['name'],
                creator=request.user,
                moves=form.cleaned_data['moves'],
                tiles=bytes(form.cleaned_data['tiles'], 'ascii')
            )
            return HttpResponseRedirect(reverse('unblock:index'))
    else:
        form = PuzzleForm()
    context = {
        'form': form, 'empty_char': empty_char, 'num_colors': num_colors,
        'num_rows': num_rows, 'num_columns': num_columns,
        'canvas_width': canvas_width, 'canvas_height': canvas_height,
        'palette_width': palette_width, 'palette_height': palette_height,
    }
    return render(request, 'unblock/create.html', context)

unblock/templates/unblock/create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}Create New Puzzle – {{ block.super }}{% endblock %}

{% block head %}
<script type="text/javascript">
    var rows = {{ num_rows }};
    var columns = {{ num_columns }};
    var emptyChar = '{{ empty_char }}';
</script>
<style type="text/css">
    .column {
        display: inline-block;
    }
</style>
{% endblock head %}

{% block content %}
<h1>Create New Puzzle</h1>
<form action="{% url 'unblock:create' %}" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <input type="submit" value="Submit">
</form>
<div>
    <canvas
      id="canvas" class="column"
      width={{ canvas_width }} height={{ canvas_height }}>
    </canvas>
    <canvas
      id="palette" class="column"
      width={{ palette_width }} height={{ palette_height }}>
    </canvas>
</div>
<script
  type="text/javascript" src="{% static 'unblock/grid.js' %}">
</script>
<script
  type="text/javascript" src="{% static 'unblock/create.js' %}">
</script>
{% endblock content %}

unblock/templates/unblock/index.html
{% extends 'base.html' %}

{% block title %}Latest Puzzles – {{ block.super }}{% endblock %}

{% block content %}
<h1>Latest Puzzles</h1>
{% if latest_puzzle_list %}
    <table>
    {% for puzzle in latest_puzzle_list %}
        <tr>
            <td><a href="{% url 'unblock:puzzle' puzzle.id %}">
                {{ puzzle.name }}
            </a></td>
            <td>
                {% if puzzle.creator %}
                {{ puzzle.creator.username }}
                {% endif %}
            </td>
            <td>
                {% if puzzle.rating %}
                {{ puzzle.rating }}★
                {% endif %}
            </td>
        </tr>
    {% endfor %}
    </table>
{% else %}
    <p>No puzzles are available.</p>
{% endif %}
<a href="{% url 'unblock:create' %}">Create new…</a>
{% endblock content %}

unblock/templates/unblock/puzzle.html
{% extends 'base.html' %}
{% load static %}

{% block title %}{{ puzzle.name }} – {{ block.super }}{% endblock %}

{% block head %}
<script type="text/javascript">
    var rawTiles = "{{ puzzle.tiles|escapejs }}";
    var rows = {{ num_rows }};
    var columns = {{ num_columns }};
    var emptyChar = '{{ empty_char }}';
</script>
<script
  type="text/javascript" defer src="{% static 'unblock/grid.js' %}">
</script>
<script
  type="text/javascript" defer src="{% static 'unblock/play.js' %}">
</script>
<style type="text/css">
    .column {
        display: inline-block;
        vertical-align: top;
    }
</style>
{% endblock head %}

{% block content %}
<div class="column">
    <h1>{{ puzzle.name }}</h1>
    {% if puzzle.creator %}
    <p>Created by {{ puzzle.creator.username }}</p>
    {% endif %}
    <p>Moves: <span id="moves_remaining">{{ puzzle.moves }}</p>
</div>
<canvas
  id="canvas" class="column"
  width={{ canvas_width }} height={{ canvas_height }}>
</canvas>
{% endblock content %}

unblock_test/templates/base.html
<!DOCTYPE html>
<html lang="en">
    <head>
        <title>{% block title %}Unblock Test{% endblock %}</title>
    {% block head %}{% endblock %}
    </head>
    <body>
        <header>
        {% comment %}
            Apparently we always have the “user” variable even if the view 
            doesn’t provide it
        {% endcomment %}
        {% if user.is_authenticated %}
            <a href="{% url 'logout' %}">Log out</a> {{ user.username }}
        {% else %}
            <a href="{% url 'login' %}">Log in</a>
        {% endif %}
        </header>
    {% block content %}{% endblock %}
    </body>
</html>